<?php return array (
  'currency_symbol' => '$6',
  'company_name' => 'sakshamap',
  'company_logo' => 'sakshamap',
  'email' => 'susheel3010@gmail.com',
  'phone_number' => '8840574997',
  'whatsapp' => '8840574990',
  'instagram' => 'susheel3010@gmail.com',
  'twitter' => 'susheel3010@gmail.com',
  'facebook' => 'susheel3010@gmail.com',
  'youtube' => 'susheel3010@gmail.com',
  'snapchat' => 'susheel3010@gmail.com',
  'footerText' => '© 2024 Sakshamapp. All rights r6eserved.',
  'welcomeText' => 'Login with Bitcoinvio helps you trade bitcoin more easily and securely throughout the world.',
  'supportText' => 'If you need support, contact us at support@bitcoinvio.com',
  'api_provider' => 'google_geminie',
  'openai_key' => NULL,
  'google_geminie_key' => '543343',
);